Add ExchangeAPI(only quote api)
gluwa/Gluwa-DotNet pull request #10
Opened 2020-11-06 10:29 UTC by kyeongminkang

Add ExchangeAPI(only quote api)

2020-11-21 00:38 UTC, chris-yoon-gluwa requested changes

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +
remove the extra space

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            if (quoteRequest.Conversion == EConversion.BtcKrwg || quoteRequest.Conversion == EConversion.BtcUsdg)
Make and extension method like IsSourceCurrencyBtc(). This is so that if we ever add BtcXXX, BtcYYY, BtcZZZ conversions, we only have to update the extension method

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            string sendingAddressSignature = getAddressSignature(sendingAddressPrivateKey, convertCurrency(quoteRequest.Conversion.Value, IsSource: true));
convertCurrency() should be an extension method instead.

ToSourceCurrency()
ToTargetCurrency()

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            string timestamp = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds().ToString();
DateTimeOffset.UtcNow? :)

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        private string getAddressSignature(string privateKey, ECurrency currency)
This is basically the same code as getBtcAddressSignature() and getGluwacoinAddressSignature() methods in GluwaClient.cs. It's better if you can take those methods out to another class and use them in this class

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        private async Task<BTCTxnSignature> getBtcTxnSignatureAsync(
BtcTxnSignatures

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        private async Task<BTCTxnSignature> getBtcTxnSignatureAsync(
getBtcTxnSignatureAsync -> getBtcTxnSignaturesAsync

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        private string getGluwaTxnSignature(
getGluwacoinReserveTxnSignature

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            string expiryBlockNumber,
Change the type to BigInteger

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        private string getContractAddress(ECurrency currency)
getGluwacoinContractAddress

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +
remove extra line here

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Models/Exchange/AcceptQuoteRequest.cs
> +        public IEnumerable<ValidationResult> Validate(MatchedOrderForQuote matchedOrders, ECurrency currency)
why do you need matchedOrders as a parameter? You already have access to it via MatchedOrders property

2020-11-21 00:38 UTC, chris-yoon-gluwa commented on SDK_dotnet/Models/Exchange/MatchedOrderForQuote.cs
> +    public sealed class MatchedOrderForQuote
AcceptQuoteMatchedOrder

2020-11-23 03:37 UTC, kyeongminkang commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            GetQuotesRequest quoteRequest)
이거 생각해보니 GetQuotesRequest가 option값인데 Overloading 함수 하나 더 추가해도 될까요? 즉, 매개변수를 currency, address, privateKey 3개만 받는 메소드요.

2020-11-24 05:18 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            GetQuotesRequest quoteRequest)
Are you talking about a method or a constructor?

2020-11-26 00:33 UTC, kyeongminkang commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            GetQuotesRequest quoteRequest)
method입니다. 덧붙이자면 GetQuotesRequest가 옵션이라는 뜻은 GetQuotesRequest는 Query할 Parameters들을 받는 객체입니다. 따라서 현재 코드로는 유저가 위의 함수를 호출할 경우, Qurey할 Parameter에 값을 넣지 않고 싶을 경우에도 빈 GetQuotesRequest를 매개 변수에 넣어야 하기 때문에 질문을 하였습니다.

2020-11-26 01:03 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            GetQuotesRequest quoteRequest)
oh ok. Then yes, that is fine. Make overloaded method.

Also, rename GetQuotesRequest to GetQuotesOptions

2020-11-27 03:41 UTC, chris-yoon-gluwa requested changes

2020-11-27 03:41 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +            GetQuotesOptions quoteRequest)
quoteRequest -> options

2020-11-27 03:41 UTC, chris-yoon-gluwa commented on SDK_dotnet/Clients/ExchangeClient.cs
> +        public async Task<Result<List<GetQuotesResponse>, ErrorResponse>> GetQuotesAsync(
For this, can't you just call the other GetQuotesAsync() inside?

2020-11-27 04:29 UTC, chris-yoon-gluwa commented on SDK_dotnet/Models/Exchange/BTCTxnSignature.cs
> +    internal sealed class BTCTxnSignature
BtcTxnSignature

2020-11-27 04:29 UTC, chris-yoon-gluwa approved these changes

2020-11-27 04:56 UTC, merged