GLA-140 Generate Nonce
gluwa/Gluwa-DotNet pull request #19
Opened 2021-05-25 07:40 UTC by kyeongminkang

GLA-140 Edit Nonce

Jira : https://gluwa.atlassian.net/browse/GLA-140

2021-05-25 16:22 UTC, kevinnguyen17 approved these changes

2021-05-25 19:48 UTC, ivansolta requested changes

2021-05-25 19:48 UTC, ivansolta commented on SDK_dotnet/Services/GluwaService.cs
> +        }
`RNGCryptoServiceProvider` needs to be disposed. See https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=net-5.0#remarks

2021-05-25 19:48 UTC, ivansolta commented on SDK_dotnet/Services/GluwaService.cs
> +            RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider();
Don't create new instance for each new number

2021-05-25 19:48 UTC, ivansolta commented on SDK_dotnet/Services/GluwaService.cs
> +                nonceString += stringNonce;
It would be better to use `StringBuilder` instead of concatenating

2021-05-25 19:48 UTC, ivansolta commented on SDK_dotnet/Services/GluwaService.cs
> +        internal static string GetNonceString()
Add parameter for nonce length with default value 75

2021-05-25 21:46 UTC, alexandre-rondeau commented on SDK_dotnet/Clients/GluwaClient.cs
> +                    nonce = nonce = GluwaService.GetNonceString();
`nonce = nonce = GluwaService.GetNonceString();`

is the middle `nonce =` necessary?

2021-05-25 21:47 UTC, alexandre-rondeau commented
Add UnitTests

2021-05-26 04:10 UTC, kyeongminkang commented
> Add UnitTests

2021-05-26 04:12 UTC, kyeongminkang commented
> Add UnitTests

Is this comment assigned to me? Unit Test is already managed by the QA team. https://gluwa.visualstudio.com/Gluwa/_git/CdUtils?path=%2FNuget.NUnitTest%2FGluwa.SDK_dotnet

2021-05-28 22:11 UTC, alexandre-rondeau approved these changes

2021-05-28 22:16 UTC, ivansolta approved these changes

2021-06-01 17:57 UTC, merged